/**
 * build.ts — the guided, Free-plan-safe agent entrypoint.
 *
 *   npx tsx build.ts
 *
 * Flow (mirrors DUNE_DASHBOARD_AGENT.md):
 *   1. Collect the two supply query IDs (from .env or interactive prompt).
 *   2. Verify each query runs and exposes a date + numeric column.
 *   3. Verify the verdicts source (optional query ID).
 *   4. Generate BUILD_SHEET.md pre-filled with the verified IDs/columns.
 *   5. Print the CanHav hand-off instructions + dashboard URL string.
 *
 * Guardrails: never creates queries/dashboards via API; never logs the key;
 * fails soft on bad query IDs (asks for a replacement instead of fabricating).
 */

import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { verifyQuery, printVerifyResult, type VerifyResult } from "./discover.ts";

const NAMESPACE = process.env.DUNE_NAMESPACE?.trim() || "wazarat";
const VERDICT_TABLE = `dune.${NAMESPACE}.canhav_agent_verdicts`;

function loadEnv(): void {
  try {
    process.loadEnvFile?.();
  } catch {
    /* .env is optional if vars are already exported */
  }
}

/** Ask for a query ID, re-verifying until it passes or the user types "skip". */
async function promptAndVerify(
  rl: ReturnType<typeof createInterface>,
  label: string,
  envValue: string | undefined,
  hint: string,
): Promise<VerifyResult | null> {
  let id = envValue?.trim();

  while (true) {
    if (!id) {
      console.log(`\n${hint}`);
      id = (await rl.question(`Paste the ${label} query ID (or "skip"): `)).trim();
    }
    if (!id || id.toLowerCase() === "skip") {
      console.log(`  ↳ skipped ${label}.`);
      return null;
    }
    if (!/^\d+$/.test(id)) {
      console.log(`  ⚠️  "${id}" isn't a numeric query ID (expected digits from dune.com/queries/<ID>).`);
      id = undefined;
      continue;
    }

    const result = await verifyQuery(label, id);
    printVerifyResult(result);
    if (result.ok) return result;

    console.log(`  ⚠️  ${label} query ${id} is not usable. Please provide an alternate ID.`);
    id = undefined; // force re-prompt
  }
}

function buildSheet(
  ethena: VerifyResult,
  usdai: VerifyResult,
  verdicts: VerifyResult | null,
): string {
  const verdictLine = verdicts
    ? `   - Verified: query ${verdicts.queryId} returned ${verdicts.rowCount} sample row(s).`
    : `   - No verdicts query ID was provided/verified. Open your saved query on ${VERDICT_TABLE}.`;

  return `# CanHav: Ethena vs USD.AI — Build Sheet

> Auto-generated by \`build.ts\`. All IDs and column names below were verified
> against Dune's latest-results API (Free-plan safe, no execution credits used).

## Verified inputs
| Chart | Query ID | Date column | Value column |
|---|---|---|---|
| sUSDe supply | ${ethena.queryId} | \`${ethena.dateColumn}\` | \`${ethena.valueColumn}\` |
| sUSDai supply | ${usdai.queryId} | \`${usdai.dateColumn}\` | \`${usdai.valueColumn}\` |
| Agent verdicts | ${verdicts ? verdicts.queryId : "(provide a saved query on " + VERDICT_TABLE + ")"} | \`ts\` | \`confidence\` |

## CanHav: Ethena vs USD.AI — assembly (Free plan, UI)

1. Open query ${ethena.queryId} → Run → New visualization → Line chart
   - X = \`${ethena.dateColumn}\`   Y = \`${ethena.valueColumn}\`   Title: "sUSDe supply"
2. Open query ${usdai.queryId} → Run → New visualization → Line chart
   - X = \`${usdai.dateColumn}\`   Y = \`${usdai.valueColumn}\`   Title: "sUSDai supply"
3. Open your verdicts query → already have a Table; add New → Scatter chart
   - X = \`ts\`   Y = \`confidence\`   Color/Group = \`severity\`   Title: "Agent verdicts"
${verdictLine}
4. New dashboard → "CanHav: Ethena vs USD.AI — Agent Insights"
   - Row 1: text widget — one-line intro
   - Row 2: sUSDe supply | sUSDai supply  (side by side)
   - Row 3: Agent verdicts scatter (full width, under the charts)
   - Row 4: verdict table (rationale text)
5. Copy dashboard URL.

## Hand-off to CanHav
Paste into CanHav → Agent page → Dune panel → Dashboard URL:
  https://dune.com/${NAMESPACE}/<your-dashboard-slug>
Then turn ON "Publish insights to Dune" and Save.
`;
}

async function main(): Promise<void> {
  loadEnv();

  console.log("=== Dune Dashboard Builder — Ethena vs USD.AI (Free-plan safe) ===");
  console.log(`Namespace: ${NAMESPACE}`);
  console.log("This tool only READS query results and writes a build sheet. It never");
  console.log("creates queries/dashboards via API and never logs your API key.\n");

  // Fail early with a friendly message if the key is missing.
  if (!process.env.DUNE_API_KEY) {
    console.error("DUNE_API_KEY is not set. Copy .env.example to .env and add your ROTATED key.");
    process.exit(1);
  }

  const rl = createInterface({ input, output });
  try {
    // STEP 1 + 2 — collect and verify the two supply queries.
    const ethena = await promptAndVerify(
      rl,
      "ethena sUSDe supply",
      process.env.ETHENA_SUPPLY_QUERY_ID,
      "Ethena supply: open a supply chart on dune.com/hildobby/ethena → URL shows dune.com/queries/<ID>.",
    );
    const usdai = await promptAndVerify(
      rl,
      "USD.AI sUSDai supply",
      process.env.USDAI_SUPPLY_QUERY_ID,
      "USD.AI supply: open the sUSDai supply chart on the USD.AI dashboard → URL shows dune.com/queries/<ID>.",
    );

    if (!ethena || !usdai) {
      console.error(
        "\nBoth supply queries are required to generate the build sheet. Re-run when you have valid IDs.",
      );
      process.exit(1);
    }

    // STEP 3 — verify the verdicts source (optional but recommended).
    const verdicts = await promptAndVerify(
      rl,
      "agent verdicts",
      process.env.VERDICTS_QUERY_ID,
      `Verdicts: paste a saved query ID that SELECTs from ${VERDICT_TABLE} (or "skip").`,
    );
    if (verdicts) {
      if (verdicts.rowCount <= 1) {
        console.log(
          "\n⚠️  WARNING: verdicts source has ≤1 row. The scatter overlay needs ~5+ rows across",
        );
        console.log(
          '   timestamps or it renders as a single dot. Enable "Publish insights to Dune" on the',
        );
        console.log("   agent and seed a few runs before assembling the dashboard.");
      }
    } else {
      console.log(
        `\nℹ️  No verdicts query verified. The build sheet will reference ${VERDICT_TABLE} generically.`,
      );
    }

    // STEP 4 — generate BUILD_SHEET.md.
    const sheet = buildSheet(ethena, usdai, verdicts);
    const sheetPath = resolve(process.cwd(), "BUILD_SHEET.md");
    writeFileSync(sheetPath, sheet, "utf8");
    console.log(`\n✅ Wrote build sheet → ${sheetPath}`);

    // STEP 5 — hand-off.
    console.log("\n========================================================");
    console.log("DONE. Follow BUILD_SHEET.md in the Dune UI to assemble the dashboard.");
    console.log("Then paste this into CanHav → Agent page → Dune panel → Dashboard URL:");
    console.log(`  https://dune.com/${NAMESPACE}/<your-dashboard-slug>`);
    console.log('Then turn ON "Publish insights to Dune" and Save.');
    console.log("========================================================");
  } finally {
    rl.close();
  }
}

main().catch((e) => {
  console.error(`\nFatal: ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
});
