/**
 * build.ts — the guided, Free-plan-safe agent entrypoint.
 *
 *   npx tsx build.ts
 *
 * Flow (mirrors DUNE_DASHBOARD_AGENT.md):
 *   1. Collect the two supply query IDs (from .env or interactive prompt).
 *   2. Verify each query runs and exposes a date + numeric column.
 *   3. Verify the verdicts source (optional query ID).
 *   4. Generate BUILD_SHEET.md pre-filled with the verified IDs/columns.
 *   5. Print the CanHav hand-off instructions + dashboard URL string.
 *
 * Guardrails: never creates queries/dashboards via API; never logs the key;
 * fails soft on bad query IDs (asks for a replacement instead of fabricating).
 */

import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { verifyQuery, printVerifyResult, type VerifyResult } from "./discover.ts";

// Load .env BEFORE reading any env-derived constants below. Node >= 20.12.
try {
  process.loadEnvFile?.();
} catch {
  /* .env is optional if vars are already exported */
}

const NAMESPACE = process.env.DUNE_NAMESPACE?.trim() || "wazarat";
const VERDICT_TABLE = `dune.${NAMESPACE}.canhav_agent_verdicts`;
const DASHBOARD_SLUG = process.env.DUNE_DASHBOARD_SLUG?.trim() || "<your-dashboard-slug>";
const DASHBOARD_URL = `https://dune.com/${NAMESPACE}/${DASHBOARD_SLUG}`;

/** Ask for a query ID, re-verifying until it passes or the user types "skip". */
async function promptAndVerify(
  rl: ReturnType<typeof createInterface>,
  label: string,
  envValue: string | undefined,
  hint: string,
): Promise<VerifyResult | null> {
  let id = envValue?.trim();

  while (true) {
    if (!id) {
      // Can only prompt in an interactive terminal. In non-interactive runs
      // (piped/CI) a missing ID means skip — don't crash on a closed readline.
      if (!input.isTTY) {
        console.log(`  ↳ no ${label} ID provided (non-interactive); skipped.`);
        return null;
      }
      console.log(`\n${hint}`);
      id = (await rl.question(`Paste the ${label} query ID (or "skip"): `)).trim();
    }
    if (!id || id.toLowerCase() === "skip") {
      console.log(`  ↳ skipped ${label}.`);
      return null;
    }
    if (!/^\d+$/.test(id)) {
      console.log(`  ⚠️  "${id}" isn't a numeric query ID (expected digits from dune.com/queries/<ID>).`);
      id = undefined;
      continue;
    }

    const result = await verifyQuery(label, id);
    printVerifyResult(result);
    if (result.ok) return result;

    console.log(`  ⚠️  ${label} query ${id} is not usable. Please provide an alternate ID.`);
    id = undefined; // force re-prompt
  }
}

interface SheetInput {
  ethena: VerifyResult;
  usdai: VerifyResult;
  usde: VerifyResult | null;
  usdaiTotal: VerifyResult | null;
  verdicts: VerifyResult | null;
}

function buildSheet({ ethena, usdai, usde, usdaiTotal, verdicts }: SheetInput): string {
  const hasSecondary = Boolean(usde && usdaiTotal);

  const verdictLine = verdicts
    ? `   - Verified: query ${verdicts.queryId} returned ${verdicts.rowCount} sample row(s).`
    : `   - No verdicts query ID was provided/verified. Open your saved query on ${VERDICT_TABLE}.`;

  // Secondary (total-supply) table rows — only included when both verified.
  const secondaryRows = hasSecondary
    ? `| USDe supply (secondary) | ${usde!.queryId} | \`${usde!.dateColumn}\` | \`${usde!.valueColumn}\` |\n| USDai supply (secondary) | ${usdaiTotal!.queryId} | \`${usdaiTotal!.dateColumn}\` | \`${usdaiTotal!.valueColumn}\` |\n`
    : "";

  // Secondary assembly steps + the extra dashboard row, only when verified.
  const secondarySteps = hasSecondary
    ? `3. Open query ${usde!.queryId} → Run → New visualization → Line chart
   - X = \`${usde!.dateColumn}\`   Y = \`${usde!.valueColumn}\`   Title: "USDe supply"
4. Open query ${usdaiTotal!.queryId} → Run → New visualization → Line chart
   - X = \`${usdaiTotal!.dateColumn}\`   Y = \`${usdaiTotal!.valueColumn}\`   Title: "USDai supply"
`
    : "";

  // Renumber the verdicts/dashboard steps based on whether the secondary row exists.
  const verdictsStepNo = hasSecondary ? 5 : 3;
  const dashStepNo = hasSecondary ? 6 : 4;
  const copyStepNo = hasSecondary ? 7 : 5;
  const secondaryDashRow = hasSecondary
    ? `   - Row 3: USDe supply | USDai supply  (secondary, side by side)\n`
    : "";
  const verdictRowNo = hasSecondary ? 4 : 3;
  const tableRowNo = hasSecondary ? 5 : 4;

  return `# CanHav: Ethena vs USD.AI — Build Sheet

> Auto-generated by \`build.ts\`. All IDs and column names below were verified
> against Dune's latest-results API (Free-plan safe, no execution credits used).

## Verified inputs
| Chart | Query ID | Date column | Value column |
|---|---|---|---|
| sUSDe supply (primary) | ${ethena.queryId} | \`${ethena.dateColumn}\` | \`${ethena.valueColumn}\` |
| sUSDai supply (primary) | ${usdai.queryId} | \`${usdai.dateColumn}\` | \`${usdai.valueColumn}\` |
${secondaryRows}| Agent verdicts | ${verdicts ? verdicts.queryId : "(provide a saved query on " + VERDICT_TABLE + ")"} | \`ts\` | \`confidence\` |

## CanHav: Ethena vs USD.AI — assembly (Free plan, UI)

1. Open query ${ethena.queryId} → Run → New visualization → Line chart
   - X = \`${ethena.dateColumn}\`   Y = \`${ethena.valueColumn}\`   Title: "sUSDe supply"
2. Open query ${usdai.queryId} → Run → New visualization → Line chart
   - X = \`${usdai.dateColumn}\`   Y = \`${usdai.valueColumn}\`   Title: "sUSDai supply"
${secondarySteps}${verdictsStepNo}. Open your verdicts query → already have a Table; add New → Scatter chart
   - X = \`ts\`   Y = \`confidence\`   Color/Group = \`severity\`   Title: "Agent verdicts"
${verdictLine}
${dashStepNo}. New dashboard → "CanHav: Ethena vs USD.AI — Agent Insights"
   - Row 1: text widget — one-line intro
   - Row 2: sUSDe supply | sUSDai supply  (primary, side by side)
${secondaryDashRow}   - Row ${verdictRowNo}: Agent verdicts scatter (full width, under the charts)
   - Row ${tableRowNo}: verdict table (rationale text)
${copyStepNo}. Copy dashboard URL.

## Hand-off to CanHav
Paste into CanHav → Agent page → Dune panel → Dashboard URL:
  ${DASHBOARD_URL}
Then turn ON "Publish insights to Dune" and Save.
`;
}

async function main(): Promise<void> {
  console.log("=== Dune Dashboard Builder — Ethena vs USD.AI (Free-plan safe) ===");
  console.log(`Namespace: ${NAMESPACE}`);
  console.log("This tool only READS query results and writes a build sheet. It never");
  console.log("creates queries/dashboards via API and never logs your API key.\n");

  // Fail early with a friendly message if the key is missing.
  if (!process.env.DUNE_API_KEY) {
    console.error("DUNE_API_KEY is not set. Copy .env.example to .env and add your ROTATED key.");
    process.exit(1);
  }

  const rl = createInterface({ input, output });
  try {
    // STEP 1 + 2 — collect and verify the two supply queries.
    const ethena = await promptAndVerify(
      rl,
      "ethena sUSDe supply",
      process.env.ETHENA_SUPPLY_QUERY_ID,
      "Ethena supply: open a supply chart on dune.com/hildobby/ethena → URL shows dune.com/queries/<ID>.",
    );
    const usdai = await promptAndVerify(
      rl,
      "USD.AI sUSDai supply",
      process.env.USDAI_SUPPLY_QUERY_ID,
      "USD.AI supply: open the sUSDai supply chart on the USD.AI dashboard → URL shows dune.com/queries/<ID>.",
    );

    if (!ethena || !usdai) {
      console.error(
        "\nBoth primary supply queries are required to generate the build sheet. Re-run when you have valid IDs.",
      );
      process.exit(1);
    }

    // STEP 2b — optional SECONDARY total-supply pair (USDe + USDai).
    // Only added to the sheet when BOTH verify; otherwise we warn and skip the row.
    const usde = await promptAndVerify(
      rl,
      "USDe supply (secondary)",
      process.env.ETHENA_SECONDARY_QUERY_ID,
      "USDe total supply (secondary): paste dune.com/queries/<ID> (or \"skip\").",
    );
    const usdaiTotal = await promptAndVerify(
      rl,
      "USDai supply (secondary)",
      process.env.USDAI_SECONDARY_QUERY_ID,
      "USDai total supply (secondary): paste dune.com/queries/<ID> (or \"skip\").",
    );
    if ((usde && !usdaiTotal) || (!usde && usdaiTotal)) {
      console.log(
        "\nℹ️  Only one secondary query verified — the secondary row needs BOTH USDe and USDai, so it will be omitted.",
      );
    }

    // STEP 3 — verify the verdicts source (optional but recommended).
    const verdicts = await promptAndVerify(
      rl,
      "agent verdicts",
      process.env.VERDICTS_QUERY_ID,
      `Verdicts: paste a saved query ID that SELECTs from ${VERDICT_TABLE} (or "skip").`,
    );
    if (verdicts) {
      if (verdicts.rowCount <= 1) {
        console.log(
          "\n⚠️  WARNING: verdicts source has ≤1 row. The scatter overlay needs ~5+ rows across",
        );
        console.log(
          '   timestamps or it renders as a single dot. Enable "Publish insights to Dune" on the',
        );
        console.log("   agent and seed a few runs before assembling the dashboard.");
      }
    } else {
      console.log(
        `\nℹ️  No verdicts query verified. The build sheet will reference ${VERDICT_TABLE} generically.`,
      );
    }

    // STEP 4 — generate BUILD_SHEET.md.
    const sheet = buildSheet({ ethena, usdai, usde, usdaiTotal, verdicts });
    const sheetPath = resolve(process.cwd(), "BUILD_SHEET.md");
    writeFileSync(sheetPath, sheet, "utf8");
    console.log(`\n✅ Wrote build sheet → ${sheetPath}`);

    // STEP 5 — hand-off.
    console.log("\n========================================================");
    console.log("DONE. Follow BUILD_SHEET.md in the Dune UI to assemble the dashboard.");
    console.log("Then paste this into CanHav → Agent page → Dune panel → Dashboard URL:");
    console.log(`  ${DASHBOARD_URL}`);
    console.log('Then turn ON "Publish insights to Dune" and Save.');
    console.log("========================================================");
  } finally {
    rl.close();
  }
}

main().catch((e) => {
  console.error(`\nFatal: ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
});
